### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xp2000csgo** [shanapu/MyJailbreak#323] opened 2018-12-28 16:07 UTC
https://crash.limetech.org/mtnuqfop47sk
https://crash.limetech.org/hja3hl74hdwd
https://crash.limetech.org/o4cdhzg5ccus

plugins list:

> 01 "Admin File Reader" (1.9.0.6269) by AlliedModders LLC
>            02 "Admin List" (1.2) by Fredd
>            03 "Anti-Flood" (1.9.0.6269) by AlliedModders LLC
>            04 "[CHAT] AnyChatFilter" (1.1.5) by Skeriiz
>            05 "Basic Chat" (1.9.0.6269) by AlliedModders LLC
>            06 "Basic Commands" (1.9.0.6269) by AlliedModders LLC
>            07 "Basic Info Triggers" (1.9.0.6269) by AlliedModders LLC
>            08 "Basic Votes" (1.9.0.6269) by AlliedModders LLC
>            09 "[CS:GO] ChatSpy" (1337) by ESK0
>            10 "Client Preferences" (1.9.0.6269) by AlliedModders LLC
>            11 "Flashlight" (1.3.63) by Mitch
>            12 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
>            13 "Hook Grab Rope Limit Use" (1.0) by Sheepdude
>            14 "Hook Grab Rope Min/Max Distance" (1.0) by Sheepdude
>            15 "Hook Grab Rope" (1.1.4) by Sheepdude, SumGuy14
>            16 "[Keys] Core" (1.4) by R1KO
>            17 "[Keys] VIP" (1.3) by R1KO
>            18 "MapChooser" (1.9.0.6269) by AlliedModders LLC
>            19 "Material Admin" (0.7.7) by Material Admin Dev Team
>            20 "Admin Menu" (0.7.7) by AlliedModders LLC
>            21 "Basic Comm Control" (0.7.7) by AlliedModders LLC
>            22 "Material Admin Checker" (0.7.7) by psychonic, Ca$h Munny, Sarabveer(VEER™)
>            23 "MyJailbreak - Arms Race" (Beta 14.1.dev-986b692) by shanapu
>            24 "MyJailbreak - Catch & Freeze" (Beta 14.1.dev-986b692) by shanapu
>            25 "MyJailbreak - CowBoy" (Beta 14.1.dev-986b692) by shanapu
>            26 "MyJailbreak - DealDamage" (Beta 14.1.dev-986b692) by shanapu
>            27 "MyJailbreak - Drunk" (Beta 14.1.dev-986b692) by shanapu
>            28 "MyJailbreak - DuckHunt" (Beta 14.1.dev-986b692) by shanapu
>            29 "MyJailbreak - War FFA" (Beta 14.1.dev-986b692) by shanapu
>            30 "MyJailbreak - Freeday" (Beta 14.1.dev-986b692) by shanapu
>            31 "MyJailbreak - Ghosts War" (Beta 14.1.dev-986b692) by shanapu
>            32 "MyJailbreak - HE Battle" (Beta 14.1.dev-986b692) by shanapu
>            33 "MyJailbreak - HideInTheDark" (Beta 14.1.dev-986b692) by shanapu
>            34 "MyJailbreak - Player HUD" (Beta 14.1.dev-986b692) by shanapu
>            35 "MyJailbreak - Icons" (Beta 14.1.dev-986b692) by shanapu
>            36 "MyJailbreak - KnifeFight" (Beta 14.1.dev-986b692) by shanapu
>            37 "MyJailbreak - Last Guard Rule" (Beta 14.1.dev-986b692) by shanapu
>            38 "MyJailbreak - Menus" (Beta 14.1.dev-986b692) by shanapu
>            39 "MyJailbreak - Core" (Beta 14.1.dev-986b692) by shanapu
>            40 "MyJailbreak - NoScope" (Beta 14.1.dev-986b692) by shanapu
>            41 "MyJailbreak - OneInTheChamber" (Beta 14.1.dev-986b692) by Hexah | shanapu
>            42 "MyJailbreak - Ratio" (Beta 14.1.dev-986b692) by shanapu, Addicted
>            43 "MyJailbreak - VIP-Core by R1KO" (Beta 14.1.dev-986b692) by shanapu
>            44 "MyJailbreak - Request" (Beta 14.1.dev-986b692) by shanapu
>            45 "MyJailbreak - Suicide Bomber" (Beta 14.1.dev-986b692) by shanapu
>            46 "MyJailbreak - Teleport War" (Beta 14.1.dev-986b692) by shanapu
>            47 "MyJailbreak - Torch Relay" (Beta 14.1.dev-986b692) by shanapu
>            48 "MyJailbreak - War" (Beta 14.1.dev-986b692) by shanapu
>            49 "MyJailbreak - Warden" (Beta 14.1.dev-986b692) by shanapu
>            50 "MyJailbreak - Weapons" (Beta 14.1.dev-986b692) by shanapu
>            51 "MyJailbreak - Zeus" (Beta 14.1.dev-986b692) by shanapu
>            52 "MyJailbreak - Zombie" (Beta 14.1.dev-986b692) by shanapu
>            53 "Nextmap" (1.9.0.6269) by AlliedModders LLC
>            54 "Map Nominations" (1.9.0.6269) by AlliedModders LLC
>            55 "No Prime Manager" (1.1.5) by OkyHp
>            56 "Реклама" (1.4) by Pheonix (????Феникс????)
>            57 "Reserved Slots" (1.9.0.6269) by AlliedModders LLC
>            58 "Rock The Vote" (1.9.0.6269) by AlliedModders LLC
>            59 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
>            60 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
>            61 "ENT_Hosties(v2.3)" (Entity) by databomb & Entity
>            62 "Sound Commands" (1.9.0.6269) by AlliedModders LLC
>            63 "SuperAdminka" (1.5.2) by Grey™
>            64 "Terrible Enable Full Alltalk" (0.02) by Sheepdude
>            65 "[VIP] Admin" (1.0.0) by R1KO
>            66 "[VIP] AURA" (1.0.1) by R1KO & Pheonix (????Феникс????)
>            67 "[VIP] Base Functions" (1.2) by R1KO (skype: vova.andrienko1)
>            68 "[VIP] Bhop" (1.0.1) by KOROVKA
>            69 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
>            70 "[VIP] Core" (2.1.1 R) by R1KO (skype: vova.andrienko1)
>            71 "[VIP] Endurance" (1.0.0) by R1KO (skype: vova.andrienko1)
>            72 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
>            73 "[VIP] Spawn Effects" (1.2) by Mr.ToNik
>            74 "[VIP] Tag" (1.1) by R1KO
>            75 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
>            76 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony

at some point sourcemod, superadminka, MyJailbreak ceases to work.
error logs writes every time on a miscellaneous. Last error log such:

> Errors: 
> MyJailbreak\armsrace.smx (MyJailbreak - Arms Race): MyJailbreak Arms Race - Can't read addons\sourcemod\configs\MyJailbreak\armsrace.ini correctly! (ImportFromFile) 
> MyJailbreak\warden.smx (MyJailbreak - Warden): MyJailbreak Warden - Can't open File: addons\sourcemod\configs\MyJailbreak\orders.cfg 
> super_adminka.smx (SuperAdminka): downloads_sound.ini file missing!!! 
> MyJailbreak\playertags.smx (MyJailbreak - PlayerTags): MyJailbreak PlayerTags - Can't open File: addons\sourcemod\configs\MyJailbreak\player_tags.cfg

Before it was not. These cfg were established on the server from the moment of installation fashion.

**Comment by shanapu** [comment] 2018-12-29 01:33
Why do you think these crashs come from MyJailbreak?
I don't see any relation in your crashlog. Well, these logs are at all very meaningless (at least for me).
When does these crashs appears? On Server/map start? on first connect? on any special action? any way to reproduce?

Remove a bunch of plugins and see if it still crash and remove more plugins to find the guilty one.

But first you should fix your errors, this errors clearly state that the plugins cannot read or open these files: 
```
MyJailbreak Arms Race - Can't read addons\sourcemod\configs\MyJailbreak\armsrace.ini correctly!
MyJailbreak Warden - Can't open File: addons\sourcemod\configs\MyJailbreak\orders.cfg
super_adminka.smx (SuperAdminka): downloads_sound.ini file missing!!!
MyJailbreak PlayerTags - Can't open File: addons\sourcemod\configs\MyJailbreak\player_tags.cfg
```
recheck these files exists.

**Comment by xp2000csgo** [comment] 2018-12-29 08:53
yes, these files exist and early editing files was not.

**Comment by xp2000csgo** [comment] 2018-12-29 10:47
L 12/29/2018 - 18:06:00: [SM] Exception reported: Entity 23 (23) is invalid
L 12/29/2018 - 18:06:00: [SM] Blaming: sm_hosties_e.smx
L 12/29/2018 - 18:06:00: [SM] Call stack trace:
L 12/29/2018 - 18:06:00: [SM]   [0] GetEntDataEnt2
L 12/29/2018 - 18:06:00: [SM]   [1] Line 1375, E:\5) Others\Projects\Compiler\sm_hosties_e\host\addons\sourcemod\scripting\include\smlib/clients.inc::Client_GetWeapon
L 12/29/2018 - 18:06:00: [SM]   [2] Line 1548, E:\5) Others\Projects\Compiler\sm_hosties_e\host\addons\sourcemod\scripting\include\smlib/clients.inc::Client_GetWeaponPlayerAmmo
L 12/29/2018 - 18:06:00: [SM]   [3] Line 6825, hosties/lastrequest.sp::Timer_StripZeus
L 12/29/2018 - 18:06:01: Error log file session closed.

**Comment by Hexer10** [comment] 2018-12-29 15:12
You should report those errors to the sm hosties (ent?) Devs, also if you're sure that those file exist make sure they also have the right ownerships

**Comment by xp2000csgo** [comment] 2018-12-29 16:11
these files exist

**Comment by Hexer10** [comment] 2019-01-01 20:05
I'll fix it tonight, tough it should happens only a few times (when a client disconnects while the timer is running)

**Comment by shanapu** [comment] 2019-01-02 19:10
@Hexer10 Thanks, but I already pushed a fix.

@xp2000csgo since this error has nothing to do with the crash you posted above and you haven't provide any further info to this crash which could explain a connection to MyJB, I close this issue. 

When you fixed your issues (missing cfg, ...), you done our suggestions from above and your server still crashs because of myjailbreak and no other plugins, please open an new issue with all relevant info.

**Closed by shanapu** 2019-01-02 19:10 UTC
Labels: need more infos
