### ISSUE TITLE
Error after csgo update 24/03/17

### ISSUE THREAD

**Issue by VendeeMurr** [shanapu/MyJailbreak#194] opened 2017-03-25 09:12 UTC
> L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: MyJailbreak/weapons.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] PrintToConsole
L 03/25/2017 - 00:26:30: [SM]   [1] Line 114, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/colors.inc::CReplyToCommand
L 03/25/2017 - 00:26:30: [SM]   [2] Line 261, addons/sourcemod/scripting/MyJailbreak/weapons.sp::Command_Weapons
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: MyJailbreak/warden.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] PrintToConsole
L 03/25/2017 - 00:26:30: [SM]   [1] Line 114, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/colors.inc::CReplyToCommand
L 03/25/2017 - 00:26:30: [SM]   [2] Line 485, addons/sourcemod/scripting/MyJailbreak/warden.sp::Command_BecomeWarden
L 03/25/2017 - 00:46:15: Error log file session closed.

**Comment by shanapu** [comment] 2017-03-25 17:11
hmmm... I can't reproduce this. 
On what version of MyJailbreak you are?
Does this error happens often or more rarely?
Do you have any 3th party plugin that use or trigger sm_weapons &/or sm_warden as comman?
Seems like colors.inc cannot handle the reply.

**Comment by VendeeMurr** [comment] 2017-03-25 17:17
L 03/25/2017 - 00:26:30: SourceMod error session started
L 03/25/2017 - 00:26:30: Info (map "ba_jail_ascention") (file "errors_20170325.log")
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: MyJailbreak/warden.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] PrintToConsole
L 03/25/2017 - 00:26:30: [SM]   [1] Line 114, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/colors.inc::CReplyToCommand
L 03/25/2017 - 00:26:30: [SM]   [2] Line 485, addons/sourcemod/scripting/MyJailbreak/warden.sp::Command_BecomeWarden
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: hookgrabrope.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] IsPlayerAlive
L 03/25/2017 - 00:26:30: [SM]   [1] Line 990, F:\Êîìïèëÿòîð\addons\sourcemod\scripting\hookgrabrope.sp::UnHookCmd
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: MyJailbreak/weapons.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] PrintToConsole
L 03/25/2017 - 00:26:30: [SM]   [1] Line 114, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/colors.inc::CReplyToCommand
L 03/25/2017 - 00:26:30: [SM]   [2] Line 261, addons/sourcemod/scripting/MyJailbreak/weapons.sp::Command_Weapons
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: MyJailbreak/warden.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] PrintToConsole
L 03/25/2017 - 00:26:30: [SM]   [1] Line 114, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/colors.inc::CReplyToCommand
L 03/25/2017 - 00:26:30: [SM]   [2] Line 485, addons/sourcemod/scripting/MyJailbreak/warden.sp::Command_BecomeWarden
L 03/25/2017 - 00:46:15: Error log file session closed.
L 03/25/2017 - 18:45:21: SourceMod error session started
L 03/25/2017 - 18:45:21: Info (map "jb_jailberd_v5_final_fix") (file "errors_20170325.log")
L 03/25/2017 - 18:45:21: [rank.smx] [Rank] ÐžÑˆÐ¸Ð±ÐºÐ° (unrecognized token: "'STEAM_1:0:18560943")
L 03/25/2017 - 19:04:43: Error log file session closed.

**Comment by shanapu** [comment] 2017-03-25 17:51
Thanks for NOT answering a single of my questions....   -.-

https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum

again:
1. On what version of MyJailbreak you are?
2. Does this error happens often or more rarely?
3. Do you have any 3th party plugin that use or trigger sm_weapons &/or sm_warden as command?

4. Any way to reproduce this?

**Comment by VendeeMurr** [comment] 2017-03-25 17:56
I've already answered all your questions by sending you an email. Check it . Here is a screenshot http://i.imgur.com/66tNMvK.png

**Comment by shanapu** [comment] 2017-03-26 01:14
sry havn't checked my mail yet. Bit confussing after posting here and then mailing ^^ but ok.
I will check it.

**Comment by VendeeMurr** [comment] 2017-03-26 06:30
Thanks!--Sent from Yandex.Mail for mobile26.03.2017, 04:14, "thomas" <notifications@github.com>:sry havn't checked my mail yet. Bit confussing after posting here and then mailing ^^ but ok.
I will check it.

**Comment by shanapu** [comment] 2017-04-14 18:29
I assume this was an temporary error...?
cause this occurs also for hookgrabrobe
```
L 03/25/2017 - 00:26:30: [SM] Exception reported: Client 12 is not in game
L 03/25/2017 - 00:26:30: [SM] Blaming: hookgrabrope.smx
L 03/25/2017 - 00:26:30: [SM] Call stack trace:
L 03/25/2017 - 00:26:30: [SM]   [0] IsPlayerAlive
L 03/25/2017 - 00:26:30: [SM]   [1] Line 990, F:\Êîìïèëÿòîð\addons\sourcemod\scripting\hookgrabrope.sp::UnHookCmd
```

does this error still appears?

**Comment by VendeeMurr** [comment] 2017-04-14 19:07
Hookgraprope error appears like everyday, there are no more myjb errors

**Comment by shanapu** [comment] 2017-04-15 00:17
I close this. If you want i can take a look at hookgrabrope, maybe i can fix this

**Closed by shanapu** 2017-04-15 00:17 UTC
Labels: error, need more infos

**Comment by VendeeMurr** [comment] 2017-04-15 05:43
It would be great if u look at hookgrabrope :)

**Comment by shanapu** [comment] 2017-04-15 12:22
htttp://shanapu.de/plugins/hookgrabrope_1.1.5.zip
